import {
  bigint, timestamp, uuid, type AnyPgColumn,
} from 'drizzle-orm/pg-core';
import { sql, type SQL } from 'drizzle-orm';

/**
 * Primary key: a UUID generated by Postgres 18's `uuidv7()` (time-ordered, so
 * B-tree indexes stay compact; clients still see a plain UUID).
 *
 * @returns The `id` column builder.
 */
export const id = () => uuid('id').primaryKey().default(sql`uuidv7()`);

/**
 * Row creation time, set by the database.
 *
 * @returns The `created_at` column builder.
 */
export const createdAt = () => (
  timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
);

/**
 * A nullable point in time (archived, used, seen, …).
 *
 * @param name - Column name.
 * @returns A `timestamptz` column builder.
 */
export const instant = (name: string) => timestamp(name, { withTimezone: true });

/**
 * An integer amount in the currency's minor unit, read as a JS number
 * (money, also quantity × 1e8 and rates × 10,000 — 03-api-design.md).
 *
 * @param name - Column name.
 * @returns A `bigint` column builder in number mode.
 */
export const integerAmount = (name: string) => bigint(name, { mode: 'number' });

/**
 * Quotes a string as a SQL literal.
 *
 * @param value - The text to quote.
 * @returns The literal, with embedded quotes doubled.
 */
export const sqlLiteral = (value: string): string => `'${value.replaceAll("'", "''")}'`;

/**
 * Builds the condition of a `CHECK (column IN (...))` for a closed set of values.
 * Values are developer constants, so they are inlined as literals in the DDL.
 *
 * @param column - The constrained column.
 * @param values - The allowed values.
 * @returns The SQL condition.
 */
export const isOneOf = (column: AnyPgColumn, values: readonly string[]): SQL => (
  sql`${column} IN (${sql.raw(values.map(sqlLiteral).join(', '))})`
);

/** Foreign-key action for rows that are parts of their parent (OQ-95, rule A). */
export const CASCADE = { onDelete: 'cascade' } as const;

/** Foreign-key action for references whose history must outlive the parent (OQ-95). */
export const SET_NULL = { onDelete: 'set null' } as const;
