import {
  PgDialect, getTableConfig, pgTable, text,
} from 'drizzle-orm/pg-core';
import { describe, expect, it } from 'vitest';
import {
  CASCADE, createdAt, id, instant, integerAmount, isOneOf, SET_NULL, sqlLiteral,
} from '../../../src/db/schema/columns';

const dialect = new PgDialect();

const probe = pgTable('probe', {
  id: id(),
  createdAt: createdAt(),
  seenAt: instant('seen_at'),
  amount: integerAmount('amount'),
  role: text('role'),
});

/**
 * Finds a column of the probe table by its SQL name.
 *
 * @param name - Column name.
 * @returns The column.
 */
const column = (name: string) => getTableConfig(probe).columns.find((c) => c.name === name)!;

describe('column builders', () => {
  it('id is a uuid primary key generated by uuidv7()', () => {
    const idColumn = column('id');

    expect(idColumn.getSQLType()).toBe('uuid');
    expect(idColumn.primary).toBe(true);
    expect(dialect.sqlToQuery(idColumn.default as never).sql).toBe('uuidv7()');
  });

  it('created_at is a required timestamptz defaulting to now()', () => {
    const created = column('created_at');

    expect(created.getSQLType()).toBe('timestamp with time zone');
    expect(created.notNull).toBe(true);
    expect(created.hasDefault).toBe(true);
  });

  it('instant is a nullable timestamptz', () => {
    expect(column('seen_at').getSQLType()).toBe('timestamp with time zone');
    expect(column('seen_at').notNull).toBe(false);
  });

  it('integerAmount is a bigint read as a JS number', () => {
    expect(column('amount').getSQLType()).toBe('bigint');
    expect(column('amount').mapFromDriverValue('123456')).toBe(123456);
  });
});

describe('sqlLiteral', () => {
  it.each([
    ['Owner', "'Owner'"],
    ["it's", "'it''s'"],
    ['', "''"],
  ])('quotes %j as %s', (value, expected) => {
    expect(sqlLiteral(value)).toBe(expected);
  });
});

describe('isOneOf', () => {
  it('builds an IN condition with the values inlined as literals', () => {
    const condition = dialect.sqlToQuery(isOneOf(probe.role, ['Owner', "O'Brien"]));

    expect(condition.sql).toBe('"probe"."role" IN (\'Owner\', \'O\'\'Brien\')');
    expect(condition.params).toEqual([]);
  });
});

describe('foreign-key actions', () => {
  it('are the two non-default ON DELETE behaviours', () => {
    expect(CASCADE).toEqual({ onDelete: 'cascade' });
    expect(SET_NULL).toEqual({ onDelete: 'set null' });
  });
});
